name: SellStick
main: com.shmkane.sellstick.SellStick
version: 9.0.0
author: shmkane
website: https://github.com/shmkane/SellStick
depend: [Vault]
softdepend: [Essentials]
commands:
   sellstick:
      description: Sell all items in a chest easily!
