# Choose between three different price interfaces, selects default if incorrect spelling/null
# PricesYML (Default), ShopGUI, Essentials
PriceSource: 'PricesYML'

Item:
  DisplayName: '&cSellStick'
  # Set the Material of the SellStick
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html for Materials
  Material: STICK
  StickLore:
    - '&a&lRight click &con a chest to sell items inside!'
  Glow: true
  # Dependent on if item is infinite
  #   Use \n for new lines
  FiniteLore: '&c%remaining% &fremaining uses'
  InfiniteLore: '&4Infinite &cuses!'
  UseSound: true

Messages:
  PluginPrefix: '&6[&eSellStick&6] '

  # When they sell the items what message should be displayed
  # Placeholders:
  #   %price% - for how much they gained
  #   %balance% - to show new balance
  SellMessage: '&cYou sold items for &f%price% &cand now have &f%balance%'

  # No Permission Message
  NoPermissionMessage: '&cSorry, you don''t have permission for this!'

  # No Territory Access
  InvalidTerritoryMessage: '&cYou can''t use sell stick here!'

  # Empty Chest
  NotWorthMessage: '&cNothing worth selling inside'

  # SellStick Break Message
  BrokenStick: '&cYour sellstick broke!(Ran out of uses)'

  # Unrelated Action
  NonSellingRelated: '&cRight click a chest!'

  # The message to send to the Admin who gave the sticks
  # Placeholders:
  #   %player% - person who will get the sellstick
  #   %amount% - amount of SellSticks that %player% will receive
  GiveMessage: '&aYou gave &e%player% &e&l%amount% &aSellSticks!'

  # Message to send to the player who received the sticks
  # Placeholders:
  #   %amount% - money that the seller receives.
  ReceiveMessage: '&aYou''ve received &e&l%amount% &asell sticks!'



