name: SellStick
main: com.shmkane.sellstick.SellStick
version: 1.0.0-SNAPSHOT
api-version: 1.20
author: shmkane, FlippinDuckMan
website: https://github.com/shmkane/SellStick
depend: [Vault]
softdepend: [Essentials, ShopGuiPlus]

commands:
  sellstick:
    description: Sell all items in a chest easily!

permissions:
  sellstick.reload:
    default: op
    description: To reload the plugin
  sellstick.use:
    default: op
    description: To use a sellstick
  sellstick.give:
    default: op
    description: Give sellstick to players

